version: "3.7"
services:
  app:
    image: dongjae93/dex
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:8000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
networks: 
    webnet: